### PR TITLE
Feat: Logos (Favicon & Navbar)

### PR DESCRIPTION
**Pull request by Zyztem**
Added the Logo to the Navbar, and also made it the favicon as well

### CODE REVIEW

**Comment by Zyztem** [comment]
Also works with dark mode

**Comment by Zyztem** [comment]
@Connor200024 any idea why i18n broke deployments?

**Comment by Zyztem** [comment]
Nvm, found it.

**Comment by Zyztem** [comment]
Question, about the Layout.js in components, is it needed? As its doing what the theme config is doing?

**Comment by Zyztem** [comment]
Sigh, What did it do this time

**Comment by Connor200024** [comment]
Is this ok now? If not then I won't push it yet.

**Comment by Zyztem** [comment]
nope

**Comment by Zyztem** [comment]
ill fix it rn

**Comment by Connor200024** [comment]
Ok let me know once done, I'll then fight with Vercel. :)

**Comment by Zyztem** [comment]
Scroll to top breaks it

**Comment by Zyztem** [comment]
Idfk why.

**Comment by Zyztem** [comment]
@Connor200024 ight, this is ready to go

**Pull request merged**
